### ISSUE TITLE
Cannot read property 'devices' of null

### ISSUE THREAD

**Issue by Kai9555** [AMoo-Miki/homebridge-tuya-lan#106]
Hello everybody,

unfortunately I have the problem that when starting homebridge in DEBUG mode the following error is displayed:

I use HOOBS version 2.1.1 and homebridge-tuya-lan v1.5.0-rc.12

Load homebridge-tuya-lan.TuyaLan
[10/24/2019, 7:37:24 AM] TypeError: Cannot read property 'devices' of null
    at new TuyaLan (/usr/local/lib/node_modules/homebridge-tuya-lan/index.js:55:43)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

[10/24/2019, 7:37:24 AM] Got SIGTERM, shutting down Homebridge...

Does somebody has any idea?

This is my config 

{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Fußbodenheizung",
                    "type": "SimpleHeater",
                    "manufacturer": "Branded",
                    "model": "Wifi Thermostat",
                    "id": "533007262462ab0851d4",
                    "key": "7dbb0ac5592726b9",
                    "temperatureDivisor": 2,
                    "maxTemperature": 35,
                    "minTemperature": 5
                }
            ]
        }

Thank You!!

**Comment by codyc1515** [comment]
You should probably delete this post or edit out your ID & Key as these are confidential to your device.

I'd say try and remove the ß letter from this and see if it works. May be that the special character does not work. You may also wish to try removing the _temperature_ parts you have specified.

Can you please post your entire config file so that we can double check there is no other issue? Make sure you remove anything confidential this time :)

**Comment by Kai9555** [comment]
Hi codyc1515,

I have removed the ß and the temperature values. The Pi restarted and again Homebridge tried in DEBUG mode started. Unfortunately with the same error.

Here is my entire config:

```javascript
{
    "bridge": {
        "name": "HOOBS",
        "username": "1234567",
        "port": 123456,
        "pin": "1234567"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "sudo": true,
            "standalone": true,
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Fussbodenheizung",
                    "type": "SimpleHeater",
                    "manufacturer": "Branded",
                    "model": "Wifi Thermostat",
                    "id": "+++++++",
                    "key": "++++++"
                }
            ]
        },
        {
            "platform": "Fritz!Box",
            "name": "My FritzBox",
            "username": "",
            "password": "++++++",
            "url": "http://fritz.box",
            "interval": 900,
            "concurrent": true,
            "devices": {
                "wifi": {
                    "name": "Guest WLAN",
                    "display": false
                }
            }
        },
        {
            "platform": "Hue",
            "users": {
                "1234": "56789",
                "1234": "56789"
            },
            "lights": true,
            "sensors": false
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "Klimaanlage",
                    "type": "switch",
                    "data": {
                        "on": "123456789",
                        "off": "123456789"
                    }
                }
            ]
        }
    ]
}
```

**Comment by codyc1515** [comment]
Your config.json file is fine. The only thing I can think of is that maybe your cachedAccessories file may be corrupted. When I checked line 55 of index.js mentioned in your error it looks like it is performing a mapping. Sorry I can't really help further. You may want to try take a back up of the file (homebridge/accessories/cachedAccessories) and remove the file then restart your Homebridge.

**Comment by Kai9555** [comment]
Ok, I tried that. Unfortunately, the same error is still displayed :(

**Comment by Kussie** [comment]
Same error here.  Everything else is working fine, but as soon as i add the Tuya package and config i get the same error.  Have tried the latest version and the rc version with no luck.   My config is:

`    {
            "platform": "TuyaLan",
            "devices": [
                {
    "name": "Power Board",
    "type": "MultiOutlet",
    "manufacturer": "Arlec",
    "model": "Smart Wifi Power Strip",
    "id": "****",
    "key": "****",
    "outletCount": 4
}
            ]
        },`

Stacktrace:
`[11/6/2019, 2:39:26 PM] TypeError: Cannot read property 'devices' of null
    at new TuyaLan (/usr/lib/node_modules/homebridge-tuya-lan/index.js:51:43)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11`

**Comment by codyc1515** [comment]
Which version of the plug-in are you using?

**Comment by Kussie** [comment]
At the moment i am using the rc version for the arlec support.

`sudo npm i -g homebridge-tuya-lan@rc`

Digging into it a little bit it would the config coming into the constructor from the props is null, at least according to my quick debugging.

**Comment by Kussie** [comment]
So on another note, without changing anything at all, just restarting the homebridge service a number of times it has just started working by itself.  🤷‍♂ 

Ahhh the joys of node >.>

**Comment by djgalati** [comment]
i'm currently having the same issues.
