### ISSUE TITLE
Problem Tuya Web Homebridge - Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined

### ISSUE THREAD

**Issue by josleng** [AMoo-Miki/homebridge-tuya-lan#118]
hello everybody, I have a led tv working with Tuya app.
i'have installed the web plugin in homebridge, I can see the led on my  iPhone but 
on homebridge I have this error:
[TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:52:44] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:52:54] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:04] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:14] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:24] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:34] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:43] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:54] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:04] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:14] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:24] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[

someone can help me?

**Comment by uberfunk** [comment]
You should post this in the [**homebridge-tuya-web**](https://github.com/basdelfos/homebridge-tuya-web/) github. This is **homebridge-tuya-lan**.
