### ISSUE TITLE
Setup not working in FreeNAS 11.2 jail

### ISSUE THREAD

**Issue by itavero** [AMoo-Miki/homebridge-tuya-lan#124]
I'm running Homebridge in a FreeNAS 11.2 jail.
When I try to follow the setup instructions, I get the following errors in the log after configuring the proxy:

```
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
Error: Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:561:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:912:23)
    at TLSSocket.emit (events.js:214:15)
    at net.js:658:12
    at Socket.done (_tls_wrap.js:479:7)
    at Object.onceWrapper (events.js:299:26)
    at Socket.emit (events.js:209:13)
    at TCP.<anonymous> (net.js:658:12) {
  code: 'ECONNRESET'
}
```

**Comment by itavero** [comment]
Just checked on my macOS machine, and I see similar errors.

**Comment by itavero** [comment]
My bad. Overlooked a step in the setup instructions: _"Enable full trust for NodeMITMProxyCA by flicking its switch"_
