### ISSUE TITLE
Tuya-lan-find gives error when attempting to launch

### ISSUE THREAD

**Issue by dbrewer333** [AMoo-Miki/homebridge-tuya-lan#129]
I've run homebridge successfully for some months now, and recently installed the homebridge-tuya-lan module in order to control some Feit color lightbulbs that are not homekit compatible.  I modified config.js of homebridge to include the tuya platform, but added no devices to it, since I don't yet have the id and key of the feit bulbs.  Homebridge continues to launch successful except to complain of there being no configured devices for tuya.  When I attempt to run tuya-lan-find, it give the following error:

/usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175
    let {address, port} = proxy.httpServer.address();
                                           ^
TypeError: Cannot read property 'address' of undefined
    at proxy.listen (/usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175:44)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:62:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:130:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:988:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3885:13
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/mkdirp/index.js:47:53
    at FSReqCallback.oncomplete (fs.js:161:21)

I'm running homebridge on Mac OS 10.15.1 on a 16" MacBook Pro.

I ran homebridge in debug mode and saw nothing pop up associated with tuya-lan-find in the console logs.

**Comment by dbrewer333** [comment]
I found it necessary to launch tuya-lan-find as root in order for it to start the proxy server.
