### ISSUE TITLE
kindly help me.. Losing my mind here.

### ISSUE THREAD

**Issue by costispavlou** [AMoo-Miki/homebridge-tuya-lan#132]
for starters.. https://www.reddit.com/r/homebridge/comments/edft9a/tuya_plugin_that_works/

I've managed to end up with this config.json but nothing seems to work. 

{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Office Shutter",
            "type": "SimpleBlinds",
            "manufacturer": "TeePao",
            "model": "Roller Switch",
            "id": "606020702cf4323eb64b",
            "ip": "164.215.19.174",
            "timeToOpen": 15,
            "timeToTighten": 15,
            "key": "3055722c675ebebf",
            "flipState": true
        },
        {
            "name": "Bedroom Shutter",
            "id": "xxx",
            "key": "xxx",
            "model": "Roller Switch",
            "ip": "164.215.19.174",
            "timeToOpen": 15,
            "timeToTighten": 15,
            "flipState": true
        },
        {
            "name": "Boiler Switch",
            "id": "xxx",
            "key": "xxx"
        }
    ]
}

**Comment by costispavlou** [comment]
I've tried to do everything from the top. 
tuya-lan-find gives the error:
   at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:95:23
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:132:12
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:995:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16 {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080

**Comment by costispavlou** [comment]
uninstalled the plugin. 
Reinstalled the plugin. 

Same error at step 5.i as posted above

**Comment by costispavlou** [comment]
reinstalled the plugin
ip changed to fixed ip's. 
discovered. but still no play

**Comment by costispavlou** [comment]
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)

**Comment by costispavlou** [comment]
uninstalled/reinstalled plugin.
changed the port of hoobs to 8000
tuya-lan-find now works with sudo

Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'

**Comment by costispavlou** [comment]
Failed to save public key to disk in /usr/local/lib/node_modules/homebridge-tuya-lan/bin/keys [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/homebridge-tuya-lan/bin/keys/a1.tuyaeu.com.public.key'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/homebridge-tuya-lan/bin/keys/a1.tuyaeu.com.public.key'

**Comment by costispavlou** [comment]
I give up.

**Comment by TheHomekitWayFinder** [comment]
@costispavlou try using this config file but make sure you put in the information of the devices and report back to see if it works as the most likely thing is that your config is wrong as there were things missing in your config.

`{
"platform": "TuyaLan",
"devices": [
{
"name": "Office Shutter",
"type": "SimpleBlinds",
"manufacturer": "TeePao",
"model": "Roller Switch",
"id": "606020702cf4323eb64b",
"key": "3055722c675ebebf",
"ip": "164.215.19.174",
"timeToOpen": 15,
"timeToTighten": 15,
"flipState": true
},
{
"name": "Bedroom Shutter",
“type”: “SimpleBlinds”,
“manufacturer”: “TeePao”,
“model”: “Roller Switch”,
"id": "xxx",
"key": "xxx",
"ip": "164.215.19.174",
"timeToOpen": 15,
"timeToTighten": 15,
"flipState": true
},
{
"name": "Boiler Switch",
“type”: “SimpleLight”,
“manufacturer”: “xxx”,
“model”: “Boiler Switch”,
"id": "xxx",
"key": "xxx"
}
]
}` 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by costispavlou** [comment]
thanks for the help. 
hoobs reports that the json is invalid so can't be saved. 

i've fixed the errors and saved successfully

[Homebridge] [TuyaAccessory] Discovery started.

[Homebridge] [12/21/2019, 16:24:05] [TuyaLan] Failed to discover Office Shutter (606020702cf4323eb64b) in time but will connect via 192.168.0.30.
[Homebridge] [12/21/2019, 16:24:05] [TuyaLan] Failed to discover Bedroom Shutter (606020702cf4323e73fa) in time but will connect via 192.168.0.22.
[Homebridge] [12/21/2019, 16:24:05] [TuyaLan] Failed to discover Boiler Switch (bfdd2fb56a0b8d19ffxsao) in time but will keep looking.
[Homebridge] [12/21/2019, 16:24:06] [TuyaLan] Connected to Office Shutter
[Homebridge] [12/21/2019, 16:24:06] [TuyaLan] Connected to Bedroom Shutter

The two shutter switches are connected but pressing on them does nothing.

**Comment by TheHomekitWayFinder** [comment]
When homebridge connects to the devices does it send a first query to the devices or not. Can you send a link to the boiler switch so that I can see what it supports and whether SimpleLight is the right thing to set it up as

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by costispavlou** [comment]
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)

**Comment by costispavlou** [comment]
The boiler switch is a switch. water heater switch so it shouldn't be a light, but an outlet

**Comment by costispavlou** [comment]
all of the shutter switches work with the tuya-web plugin but as lights. 
I want to have the blind icon and their functionality, that's why I'm busting my head to make this work.

the water switch works perfectly as outlet.

**Comment by costispavlou** [comment]
https://www.aliexpress.com/item/Tuya-Smart-Life-WiFi-Curtain-Blind-Switch-for-Roller-Shutter-Electric-motor-Google-Home-Alexa-Echo/32963064005.html?

https://www.aliexpress.com/item/Tuya-Smart-Life-WiFi-Curtain-Blind-Switch-for-Roller-Shutter-Electric-motor-Google-Home-Alexa-Echo/32963064005.html?

**Comment by costispavlou** [comment]
nothing works. Whatever I do it doesn't want to work. 
And if connected, toggling does nothing.

**Comment by costispavlou** [comment]
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Failed to discover Office Shutter (606020702cf4323eb64b) in time but will connect via 192.168.0.30.
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Failed to discover Bedroom Shutter (606020702cf4323e73fa) in time but will connect via 192.168.0.22.
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Bedroom Shutter has a different type (14 vs 7)
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Unregistering Bedroom Shutter
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Failed to discover Boiler Switch (bfdd2fb56a0b8d19ffxsao) in time but will keep looking.
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Connected to Office Shutter
[Homebridge] [12/21/2019, 17:15:08] [TuyaLan] Connected to Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Office Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Office Shutter
[Homebridge] [TuyaAccessory] Socket had a problem and will reconnect to Bedroom Shutter (Error: ERR_PING_TIMED_OUT)
[Homebridge] [TuyaAccessory] Closed connection with Bedroom Shutter

**Comment by costispavlou** [comment]
{
    "platform": "TuyaLan",
    "devices": [
        {
            "name": "Office Shutter",
            "type": "SimpleBlinds",
            "manufacturer": "bleh",
            "model": "Roller Switch",
            "ip": "192.168.0.30",
            "id": "*****",
            "key": "********",
            "timeToOpen": 15,
            "timeToTighten": 15            
        },
        {
            "name": "Bedroom Shutter",
            "type": "Outlet",
            "manufacturer": "whoeverdidthis",
            "model": "Roller Switch",
            "id": "***",
            "ip": "192.168.0.22",
            "key": "****",
            "timeToOpen": 15,
            "timeToTighten": 15,
            "flipState": true
        },
        {
            "name": "Boiler Switch",
            "type": "Outlet",
            "manufacturer": "me",
            "model": "Outlet",
            "ip": "192.168.0.11",
            "id": "*****",
            "key": "*******"
        }
    ]
}

**Comment by costispavlou** [comment]
I'm using hoobs by the way. If that matters somehow.

**Comment by costispavlou** [comment]
the id must be the virtualid ? or the mac address? 

"id": "**606020702**xxxxxxxx",
or just the xxx

**Comment by costispavlou** [comment]
[Homebridge] [TuyaAccessory] Odd message from Office Shutter with command 8: { cmd: 8, data: 'n³Þê\tbãG§0Ë\u0005\u001cK' }

**Comment by TheHomekitWayFinder** [comment]
The id must be the virtual if of the device that you can find in the TuyaSmart app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by costispavlou** [comment]
> The id must be the virtual if of the device that you can find in the TuyaSmart app
> 
> Sent with [GitHawk](http://githawk.com)

everything is correct. The plugin just doesn't want to work.

**Comment by eshventures** [comment]
Exact same problem...plugin has Cleary been neglected by the developers. It doesn't work anymore. My devices are correctly setup with Virtual ID and Key. They show in Homekit but do nothing. Tried everything include static IP for each device. Will have to unfortunately go back to Tuya Web which I don't want to do.

**Comment by ajayk24** [comment]
So i was going crazy for a few days with the exact same issue and finally, I managed to figure it out. I am using homebridge on a raspberry pi 4 and here's how I made it to work.

In the plugins section, click on the settings icon of the homebridge tuya lan plugin and select install previous version and from there select v1.5.0-rc.12-rc (which is actually above the v1.4.0). After this restart the homebridge and the connections should now work.

**Comment by tproenca** [comment]
> So i was going crazy for a few days with the exact same issue and finally, I managed to figure it out. I am using homebridge on a raspberry pi 4 and here's how I made it to work.
> 
> In the plugins section, click on the settings icon of the homebridge tuya lan plugin and select install previous version and from there select v1.5.0-rc.12-rc (which is actually above the v1.4.0). After this restart the homebridge and the connections should now work.

It worked for me. Thank you so much!!!

**Comment by eshventures** [comment]
> So i was going crazy for a few days with the exact same issue and finally, I managed to figure it out. I am using homebridge on a raspberry pi 4 and here's how I made it to work.
> 
> In the plugins section, click on the settings icon of the homebridge tuya lan plugin and select install previous version and from there select v1.5.0-rc.12-rc (which is actually above the v1.4.0). After this restart the homebridge and the connections should now work.

Thanks so much. This certainly sounds like the solution! However, I’m using hoobs…Does anyone know how to do this with hoobs? Thanks in advance for any guidance.
