### ISSUE TITLE
Setup instructions please help

### ISSUE THREAD

**Issue by PerthSteve** [AMoo-Miki/homebridge-tuya-lan#137]
It's late, and I'm struggling with the [setup instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) - Step 5.i.

Where am I running `tuya-lan-find` from? I have homebridge running in docker, and I'm trying to use the terminal of the homebridge-config-ui-x browser. All I get is "command not found".

**Comment by ilovecats516** [comment]
I ran it from /var/lib/homebridge

Not sure if that helps.

**Comment by TheHomekitWayFinder** [comment]
You shouldn’t have homebridge open when trying to do Tuya-lan-find. You should be running it from your command line on whatever platform you are running it on and you should just be able to enter Tuya-lan-find and it should run.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PerthSteve** [comment]
> You shouldn’t have homebridge open when trying to do Tuya-lan-find. You should be running it from your command line on whatever platform you are running it on and you should just be able to enter Tuya-lan-find and it should run.
> 
> Sent with [GitHawk](http://githawk.com)

Sorry took a while to get back to this. 
So I installed manually inside the docker terminal (even though it’s included in my docker-compose file) and now I can run this command. However, I get an error:

/homebridge # tuya-lan-find
Error: Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:95:23
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:132:12
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:995:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16 {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080
}

So the port is already in use. Not quite sure how to proceed. Thanks for your assistance!

**Comment by jim788e** [comment]
> 
> 
> > You shouldn’t have homebridge open when trying to do Tuya-lan-find. You should be running it from your command line on whatever platform you are running it on and you should just be able to enter Tuya-lan-find and it should run.
> > Sent with [GitHawk](http://githawk.com)
> 
> Sorry took a while to get back to this.
> So I installed manually inside the docker terminal (even though it’s included in my docker-compose file) and now I can run this command. However, I get an error:
> 
> /homebridge # tuya-lan-find
> Error: Error: listen EADDRINUSE: address already in use :::8080
> at Server.setupListenHandle [as _listen2] (net.js:1301:14)
> at listenInCluster (net.js:1349:12)
> at Server.listen (net.js:1437:7)
> at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:95:23
> at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:132:12
> at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
> at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
> at replenish (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:1006:25)
> at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:995:17)
> at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16 {
> code: 'EADDRINUSE',
> errno: 'EADDRINUSE',
> syscall: 'listen',
> address: '::',
> port: 8080
> }
> 
> So the port is already in use. Not quite sure how to proceed. Thanks for your assistance!

change the port from homebridge or any program use 8080 port
try sudo lsof -i :8080
