### ISSUE TITLE
Issue running multiple instances of Homebridge with PM2

### ISSUE THREAD

**Issue by npburns224** [AMoo-Miki/homebridge-tuya-lan#140]
I have a separate instance of Homebridge running in PM2 for each plugin I have installed, each with their own separate config file. After installing the Tuya-Lan plugin and pointing PM2 to the directory containing its config file, I receive this output in the log:

`[1/1/2020, 4:08:43 PM] TypeError: Cannot read property 'devices' of null
	at new TuyaLan (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/homebridge-tuya-lan/index.js:51:43)
	at Server._loadDynamicPlatforms (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/homebridge/lib/server.js:358:30)
	at Server.run (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/homebridge/lib/server.js:92:8)
	at module.exports (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/homebridge/lib/cli.js:59:10)
	at Object.<anonymous> (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/homebridge/bin/homebridge:17:22)
	at Module._compile (internal/modules/cjs/loader.js:1139:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
	at Module.load (internal/modules/cjs/loader.js:988:32)
	at Function.Module._load (internal/modules/cjs/loader.js:896:14)
	at Object.<anonymous> (/home/pi/.nvm/versions/node/v13.5.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)`

The only way I'm able to get this plugin working is by adding its config information to each of the individual config files belonging to the other running instances of Homebridge.

**Comment by iRayanKhan** [comment]
See PR #105, fixed it for me

**Comment by npburns224** [comment]
Unfortunately I’m still experiencing the same issue with v1.5.0. Unless I have `{ "platform": "TuyaLan", "devices": [] }` defined in the config file of every instance, Homebridge will start an infinite loop of crashing and restarting. 
I gave the `rc` version a go while I was at it with similar results. I’ll continue to poke around when I’m back at the computer to see if there’s not something else possibly causing issues.

**Comment by iRayanKhan** [comment]
@npburns224 Download the PR, it hasn't been merged in yet.
