### ISSUE TITLE
Problem with Setup: Error when trying to find ID and Key

### ISSUE THREAD

**Issue by francisables** [AMoo-Miki/homebridge-tuya-lan#142]
Hi,

After installing the profile on my phone and changing the info on my wifi connection to the proxy listed in Terminal I'm presented with an error message in terminal rather than the ID and Key for my Tuya linked product. Below is a snippet of the error:

Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:915:23)
    at TLSSocket.emit (events.js:215:7)
    at net.js:659:12
    at Socket.done (_tls_wrap.js:481:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}

I've tried many ways of doing the process, unlinking/linking the product to the TuyaApp, uninstalling/installing the plugin/homebridge/Mac OS (I needed a clean-out anyway), but nothing is making a difference.

Any help would be great, Thanks!

**Comment by mazafra1** [comment]
Same here!! I'm running homebridge inside a docker container on libreelec

**Comment by mazafra1** [comment]
I did a npm i -g homebridge-tuya-lan@rc as suggested in other threads and now the "Odd message with command 8" that I saw in the logs disappeared. Now it shows:
[TuyaAccessory] Odd message from Mesa with command 8: jKt10c0kb6iqXK0/yY+BcxgrEpETFhD1jhUeYUQ22QI5q5755c/3+rpDkBf3/SnIDkIJijI0f7YTBxdPkROTYUG+7OzqAGxN9oTwMDmGids=
[TuyaAccessory] Raw message from Mesa (3.1) with command 8: 000055aa00000000000000080000008b00000000332e31363833646136613666396634366230656a4b74313063306b62366971584b302f79592b426378677245704554466844316a68556559555132325149357135373535632f332b7270446b4266332f536e49446b494a696a493066375954427864506b524f545955472b374f7a714147784e396f54774d446d476964733ddbd4e7d80000aa55

Still, not able to pair the device. tuya-lan-find script doesn't not log anything after "certificate request".

**Comment by ScottEgan** [comment]
This probably will not be much help, but this issue is also being discussed here: https://github.com/codetheweb/tuyapi/issues/280
Seems as though a Tuya app update has caused issues?

**Comment by mazafra1** [comment]
Yes, it seems pretty much so. I can confirm that tuya app version 3.14 on iOS 13 doesn’t work anymore.

**Comment by matbor** [comment]
Same problem here.

It still discovers the id/key in if I set it up with the ‘Brilliant Smart’ App, but different (code 8 errors) API so homebridge cant talk to it by the looks of it.

**Comment by philmor90** [comment]
Still working with "Ucomen Home" App on iOS.

**Comment by mazafra1** [comment]
> Same problem here.
> 
> It still discovers the id/key in if I set it up with the ‘Brilliant Smart’ App, but different (code 8 errors) API so homebridge cant talk to it by the looks of it.

On iOS? How do you do to add the wifi socket to that app?

**Comment by adski11892** [comment]
I get this error when I try to run the terminal command

hoobs@hoobs:/var/lib/homebridge $ tuya-lan-find
Error: { Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:95:23
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:132:12
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:995:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080 }

**Comment by earlywaff** [comment]
Move your homebridge to port 8081 and reboot. And then repeat the command again for tuyalan

**Comment by adski11892** [comment]
Ah many thanks, did that and got the ID and key.  All working ok now in homebridge.  Huge thanks.

**Comment by earlywaff** [comment]
Please unsubscribe as soon as you finish this is very important. Since apparently the plugin does not work) I asked many people to install this plugin and they all had homebrige crash)

**Comment by earlywaff** [comment]
And sorry for my English)

**Comment by ApopheniaPays** [comment]
ucomen home app doesn't work anymore. Jesus, I can't believe how many hours it's taking trying to get a single bulb recognized. Glad I decided to "save some money" buy buying bulbs thinking Homebridge was actually going to allow me to connect them to Homekit. Six hours work and nothing yet, haven't yet found a single set of instructions anywhere online that works. 

Is this abandonware? Could someone please provide working instructions to get the ID/key?

**Comment by nickd-beemit** [comment]
Pretty sure this is due to Tuya App now doing certificate pinning, and I don't think there's an easy way around it. Also tried with Charles Proxy.
