### ISSUE TITLE
I am running HOOBS, how do I execute tuya-lan-find? 

### ISSUE THREAD

**Issue by alifmusa** [AMoo-Miki/homebridge-tuya-lan#172]
Since HOOBS doesnt use terminal, how do I execute tuya-lan-find from HOOBS interface?

**Comment by spickstone** [comment]
This probably defeats the purpose of getting an appliance but as far as I can tell you only need to do the setup (find the key and id) once for each device, so you could run a software version temporarily and then add the config to your HOOBS instance.

**Comment by alifmusa** [comment]
Hi, once I install the plug in, do I just type execute “tuya-lan-find” in the Terminal? Can you please give me a little more detail on getting id and key. I’m new to this and coding.

**Comment by nbaosullivan** [comment]
Hey @alifmusa, I'm just going through these steps myself and in my instance, the Hoobs server is running on the default port `tuya-lan-find` uses (8080), so I received the following error
```
Error: Error: listen EADDRINUSE: address already in use :::8080
```
To fix this, I had to update to the latest `rc` version:

```
sudo npm i -g homebridge-tuya-lan@rc
```

and then re-run the command specifying an available port:
```
tuya-lan-find --port 8081
```
That generated the QR code as expected.

**Comment by BrennonTWilliams** [comment]
@nbaosullivan I replicated your steps, however it seems that the --port flag isn't being accepted as I get the same result (I'm running this in the HOOBS terminal). What am I missing? Do I need to relaunch Tuya Lan or do something else first?

```
hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm i -g homebridge-tuya-lan@rc
/usr/local/bin/tuya-lan-find -> /usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js
+ homebridge-tuya-lan@1.5.0-rc.12
added 61 packages from 53 contributors in 20.192s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.13.4 -> 6.14.4      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.4   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

hoobs@hoobs:/home/hoobs/.hoobs/etc $ tuya-lan-find --port 8081
Error: Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at /home/hoobs/.hoobs/node_modules/http-mitm-proxy/lib/proxy.js:95:23
    at /home/hoobs/.hoobs/node_modules/http-mitm-proxy/lib/ca.js:132:12
    at /home/hoobs/.hoobs/node_modules/async/dist/async.js:3888:9
    at /home/hoobs/.hoobs/node_modules/async/dist/async.js:473:16
    at replenish (/home/hoobs/.hoobs/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/home/hoobs/.hoobs/node_modules/async/dist/async.js:995:17)
    at /home/hoobs/.hoobs/node_modules/async/dist/async.js:969:16 {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080
}
```

**Comment by Thebeatman** [comment]
hi i also cant seem to run the change of port and get this:
Error starting proxy: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-tuya-lan/bin/certs'
