### ISSUE TITLE
Issue find ID and Key of the device using tuya-lan-find

### ISSUE THREAD

**Issue by singhrajtomar** [AMoo-Miki/homebridge-tuya-lan#181]
Hello,
I have properly followed all the steps mentioned in the thread. As soon as i configure everything and launch Tuya app, I get an error on my console. "Error: Error: Socket Hang Up". The error is followed by more quotes which keep on increasing whenever i pull refresh, I am new to this so please guide me accordingly.
Below is the response:
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}
Error: Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1056:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}

Thank You

**Comment by TheHomekitWayFinder** [comment]
Please note that tuya-lan-find is currently not working with the TuyaSmart app however is working with some other apps such as cocoon connect, ucomen home, Kogan smarterhome. Also if you need  support with adding new devices then you are better to move to using homebridge-tuya-platform as it is being actively updated. Your config will stay the same and the process it’s just that it is being updated more regularly than this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jp-lno** [comment]
You can use an old application .apk on a rooted Android to find the key in an xml file. 
I'm using Tuya switch to control my rolling shutter with homebridge and with `1.5.0-rc.12` everything is working for me :).

Here is my homebridge config : 

>         {
>             "platform": "TuyaLan",
>             "devices": [
>                 {
>                     "name": "Roller shutter",
>                     "type": "SimpleBlinds",
>                     "manufacturer": "Etersky",
>                     "model": "WF-CS01",
>                     "id": "<devide-id>",
>                     "key": "<device-key>",
>                     "timeToOpen": 17,
>                     "timeToTighten": 4,
>                     "flipState": false,
>                     "cmdOpen": "on",
>                     "cmdClose": "off",
>                     "cmdStop": "stop",
>                     "sendEmptyUpdate": true
>                 }
>             ]
>         }

**Comment by singhrajtomar** [comment]
> You can use an old application .apk on a rooted Android to find the key in an xml file.
> I'm using Tuya switch to control my rolling shutter with homebridge and with `1.5.0-rc.12` everything is working for me :).
> 
> Here is my homebridge config :
> 
> > ```
> >     {
> >         "platform": "TuyaLan",
> >         "devices": [
> >             {
> >                 "name": "Roller shutter",
> >                 "type": "SimpleBlinds",
> >                 "manufacturer": "Etersky",
> >                 "model": "WF-CS01",
> >                 "id": "<devide-id>",
> >                 "key": "<device-key>",
> >                 "timeToOpen": 17,
> >                 "timeToTighten": 4,
> >                 "flipState": false,
> >                 "cmdOpen": "on",
> >                 "cmdClose": "off",
> >                 "cmdStop": "stop",
> >                 "sendEmptyUpdate": true
> >             }
> >         ]
> >     }
> > ```

Thank You for answering to my query. Can you please tell me which version should i look for?

**Comment by singhrajtomar** [comment]
> Please note that tuya-lan-find is currently not working with the TuyaSmart app however is working with some other apps such as cocoon connect, ucomen home, Kogan smarterhome. Also if you need support with adding new devices then you are better to move to using homebridge-tuya-platform as it is being actively updated. Your config will stay the same and the process it’s just that it is being updated more regularly than this
> 
> Sent with [GitHawk](http://githawk.com)

Thank You for replying to my query
You mean to say that I can pair the same device in other apps and then use tuya-lan-find command with the same proxy method to find the id and key?

**Comment by jp-lno** [comment]
It depend. If you use a rooted android smartphone you can install an old .apk of the Tuya app and the proxy method will work. 
But if like me you don’t have an android device. You can use an android emulator in your computer. Install the first 3.xx smart life app and find in android data an xml file containing all the keys from device synced to your Tuya account. 
I’ve used Bluestack with root access to find this xml file with keys.  I will try to retrieve the blog article where I found this method.

**Comment by singhrajtomar** [comment]
> It depend. If you use a rooted android smartphone you can install an old .apk of the Tuya app and the proxy method will work.
> But if like me you don’t have an android device. You can use an android emulator in your computer. Install the first 3.xx smart life app and find in android data an xml file containing all the keys from device synced to your Tuya account.
> I’ve used Bluestack with root access to find this xml file with keys. I will try to retrieve the blog article where I found this method.

PLease share if you get the blog article link

Thank You

**Comment by singhrajtomar** [comment]
> It depend. If you use a rooted android smartphone you can install an old .apk of the Tuya app and the proxy method will work.
> But if like me you don’t have an android device. You can use an android emulator in your computer. Install the first 3.xx smart life app and find in android data an xml file containing all the keys from device synced to your Tuya account.
> I’ve used Bluestack with root access to find this xml file with keys. I will try to retrieve the blog article where I found this method.

I have the bluestacks with root access ready. the oldest version of smart life i could find was 3.7.1. Please let me know if that would work or not

**Comment by jp-lno** [comment]
You just need to connect to your account sync your devices and go to
/data/data/com.tuya.smartlife/shared_prefs

You will have a .xml file preferences_global_key_<some chars and numbers>.xml containing your device localKey.

[Here ](https://community.openhab.org/t/step-by-step-guide-for-adding-tuya-bulbs-wi-fi-smart-led-smart-life-app-to-oh2-using-tuya-mqtt-js-by-agentk/59371)is the link of the original blog article

**Comment by funtik039** [comment]
Proxy works perfect whis Smart Life Smart Living_v3.7.5_apkpure.com.apk

**Comment by singhrajtomar** [comment]
> Proxy works perfect whis Smart Life Smart Living_v3.7.5_apkpure.com.apk

i can get v3.7.5 from apk pure. please let me know how can i proceed with the proxy trick

Thank You

**Comment by singhrajtomar** [comment]
> You just need to connect to your account sync your devices and go to
> /data/data/com.tuya.smartlife/shared_prefs
> 
> You will have a .xml file preferences_global_key_.xml containing your device localKey.
> 
> [Here ](https://community.openhab.org/t/step-by-step-guide-for-adding-tuya-bulbs-wi-fi-smart-led-smart-life-app-to-oh2-using-tuya-mqtt-js-by-agentk/59371)is the link of the original blog article

Apologies for replying late. Sure i will look into it and let you know

Thank You

**Comment by funtik039** [comment]
> > Proxy works perfect whis Smart Life Smart Living_v3.7.5_apkpure.com.apk
> 
> i can get v3.7.5 from apk pure. please let me know how can i proceed with the proxy trick
> 
> Thank You

1. Install Smart Living_v3.7.5 to your android device.
2. Run tuya-lan-find --schema
3. Watch this video: https://youtu.be/1GV5nQ5LB70 I think it will help, but all on Russian lang. My phone on Android 10.

I got many errors too, but get id and key.

**Comment by singhrajtomar** [comment]
> You just need to connect to your account sync your devices and go to
> /data/data/com.tuya.smartlife/shared_prefs
> 
> You will have a .xml file preferences_global_key_.xml containing your device localKey.
> 
> [Here ](https://community.openhab.org/t/step-by-step-guide-for-adding-tuya-bulbs-wi-fi-smart-led-smart-life-app-to-oh2-using-tuya-mqtt-js-by-agentk/59371)is the link of the original blog article

Hello,
I got the ID and Key using method from the blog. Thank You for sharing. @funtik039 we can get ID and key from this method as well and I find it less complicated. Thank You for sharing your method as well

**Comment by singhrajtomar** [comment]
> You can use an old application .apk on a rooted Android to find the key in an xml file.
> I'm using Tuya switch to control my rolling shutter with homebridge and with `1.5.0-rc.12` everything is working for me :).
> 
> Here is my homebridge config :
> 
> > ```
> >     {
> >         "platform": "TuyaLan",
> >         "devices": [
> >             {
> >                 "name": "Roller shutter",
> >                 "type": "SimpleBlinds",
> >                 "manufacturer": "Etersky",
> >                 "model": "WF-CS01",
> >                 "id": "<devide-id>",
> >                 "key": "<device-key>",
> >                 "timeToOpen": 17,
> >                 "timeToTighten": 4,
> >                 "flipState": false,
> >                 "cmdOpen": "on",
> >                 "cmdClose": "off",
> >                 "cmdStop": "stop",
> >                 "sendEmptyUpdate": true
> >             }
> >         ]
> >     }
> > ```

Hello @jplongo ,
I need some more help in setting config file. I have a garage door opener which i will use to operate a gate. That garage door controller also has sensors to detect whether the gate is closed or not. The gate opener however, according to the current scenario (remote configuration) closes the gate automatically after some time. but i doubt the sensor will update the data to home-bridge. The config file you shared, manually sets the time to open and stay. I have some thoughts related to it.
1. when I give command to the device, the device the gate opener should open but after that it must be up to the gate opener only to control the gate on itself. The device after giving the open command should only send back the sensor data of gate whether being opened or closed. There can be an exception where i even give the close command manually. How can we make this work?

2. (not important) I was unable to get the device type so I used Bind Opener only. due to this the gate opener shows as bind opener on apple home app (which is obvious). can you tell which device should i include in the field in order to make this show as a gate?

I am new to all this stuff and you seem experienced in homebridge. Hope you would help me this

Thank You

**Comment by jp-lno** [comment]
Be careful, my config is used to open/close my rolling shutter. Device is "SimpleBLinds".
According to project documentation, devices settings are differents if you want to control [Garage doors](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Supported-Devices#garage-doors)
