### ISSUE TITLE
tuya-lan-find Error: Unable to Get Issuer Cert Locally

### ISSUE THREAD

**Issue by BrennonTWilliams** [AMoo-Miki/homebridge-tuya-lan#183]
I followed the Setup instructions, only with Ucomen Home 1.1.13 instead of TuyaSmart due to the problem refrenced in other issues.

After configuring the proxy and opening the Ucomen Home app, my terminal produces the following error:

```
Intercepted certificate request
Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY { Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY { Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```
How can I resolve this to get the Ids and Keys of my smart lights?

**Comment by BrennonTWilliams** [comment]
I was able to resolve this by using the Smarter Home app instead of Ucomen. I imagine Ucomen 1.1.13 changed how they communicated the payload of ids and tokens.
