### ISSUE TITLE
socket hang up error

### ISSUE THREAD

**Issue by eagleotstar** [AMoo-Miki/homebridge-tuya-lan#186]
I keep getting this error when I try to do the given steps as soon as I open the tuya smart app
Error: Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1038:23)
    at TLSSocket.emit (events.js:322:22)
    at net.js:672:12
    at Socket.done (_tls_wrap.js:557:7)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at TCP.<anonymous> (net.js:672:12) {
  code: 'ECONNRESET'

**Comment by KevinDevs** [comment]
same here

**Comment by Daltonstudio** [comment]
Appearently Tuya made changes to their app and the discovery doesn't work anymore.
I found one app where it works with and that is LSC Smart Connect.

Use that app to find the keys, and important. Don't update that app.

**Comment by mrmaximas** [comment]
> Appearently Tuya made changes to their app and the discovery doesn't work anymore.
> I found one app where it works with and that is LSC Smart Connect.
> 
> Use that app to find the keys, and important. Don't update that app.

same shit in Cocoon & LSC

**Comment by thilomaurer** [comment]
And now?

**Comment by thilomaurer** [comment]
The socket hang up does not appear for the latest release v1.5.0-rc.12.
The tool is waiting for occurence of `tuya.m.my.group.device.list`. But the new message format seems encrypted, as it look like this:
`
{"result":"mAUGX9o6vraeeqXd94LT8LJXQ+zqYP42VVhO59xviFf8NpUL1ioY08phTt8qCbUc34/bEXj43Jp9b94WmzBdvUFcXi/dEcv/CgK4UEV9iL/4g39fqivvnlwjftHAfBPYXOalteE1OyXqF+MBRpKU+J8Oy3PdttdRXqW/Sux/stgy2+BhTmCpLpiulmhciNoicwzdZ9rdUBlSrfQLFRvzI9nYnNo1t8qiveweaT88yB21QNZWM2hclL0XfTKWpk2UfDAlgX36yTEPBAACluo7KofnukzLgEIs77VpjlOlRKW+zC8yN3QqaSIjAJG7+IaDsAfCZ0fF+ly3FBASL9rmeGPagfLRD+dcf4rdPKiNwTGFCmRc5eulcXTgHZzEm0KHHYv+zBhhoYRAdhNvXxoNWG74n8ifgBIEw7sgwTZkr4YHfwkHFCM4HKa5yyaZ3LccU76WW0w8EQF8d+4RdkWAQdIf7I1G7TYWbpjr4PUZbEseH7mWB/YovhHaBqM3zjwlXOalteE1OyXqF+MBRpKU+J8Oy3PdttdRXqW/Sux/stgy2+BhTmCpLpiulmhciNoi6OQ3xfofi2+vBc3Lw+EkV6P3R9e8WKHaQuZmMHyTCxqNC7c2owis5HKLy3UBj0hFXORhlthiu5FiwSt16nKoszk3kqfYQ5sl6pJOLlrmHRsEZJuCAGyHNA4+W/khGrsr6OHWwCU/UD7C3asuo3OEHpRcK/6jNmR0v8ulkZ8yWrwrq6kr0NEfS6B7u7z/O2LaBFVXDPCuKGXGick0cyTKnD6OboSCGQRiCi+ZKPqAMDAbevCzkM0Sh3zXsT9Ta9+sfc4igfMYxiKNM1/ymQCAvz2EgWGNrNAeRiaJDANsDR+x7/EB1sc2uDBxtfPhdI7oP7exNaMaOzN9uInpEGHQZ67yQYukZtvXUWGdHVxHCtAnwGMHVvF9sPBESYNIsn8NXS9kqpocJtI/4Hx4MZ7UX6YVhnxd7VTE2QPw/7ynAznm2HRTfWcExw5iRJQA1N4s+gMTSVpHdxA3EeXsKX2Fhmko7AD6eFT35tghXJV7U2u5VkA02Vj0FHfydEtAM4LH2LqJ9WkRsyvc7zCbA1H+BQ2B+m0pV0kqpKcgNGj78MahO4Bg4Jier1aqltYYpa+kRXHiP8qCNogbhdU3cakrsjDgV3CGJZ6tnOO75lQb0qd/v/Lds9+Dvt/Ikz6hc5XpYn7TOCCGgtP/NPTe8faDMGyt2cY3NFr/EMOV9pwsQfdPU1WTHospmRa5U1iDEQ4eeB64ct1bQ7xKnKAABl7WOB2QrisIrv+HDl1crRlYCjeqohUehHiq+lK4GDgZoEijitUAZd9cW4WQHbQiO3XjnKETeFD70MskPLvUZjDIqoTNezObStrOyBef79MSWYQOHD56IHvgSv5iW5nkd23ilJo7i+3izFkZaOPg0k9xbcscZAHWUNjThobtOzqgBYLNxUlhXK4r7iK9ZThe2dq+R6xQE1dogpJB3sFuWE0vx8XoSqB13WV1TlyoWFh4pdHp0WmspDDzhCnNyzSEV1THn/bVSRTvdxmwKh8lWYwHdQTrmyE+Av/+tQGUxwNus5gQ1IcIjmZutOKU5K4mVv3IxVUjuN2x2HYbsZLT19Y1DftrBtmt99sVH419UJXz03CG","t":1590867430,"sign":"e3a95612d0680282cd030cb150d91fd4"}`

**Comment by lalitkoli** [comment]
> The socket hang up does not appear for the latest release v1.5.0-rc.12.
> The tool is waiting for occurence of `tuya.m.my.group.device.list`. But the new message format seems encrypted, as it look like this:
> ` {"result":"mAUGX9o6vraeeqXd94LT8LJXQ+zqYP42VVhO59xviFf8NpUL1ioY08phTt8qCbUc34/bEXj43Jp9b94WmzBdvUFcXi/dEcv/CgK4UEV9iL/4g39fqivvnlwjftHAfBPYXOalteE1OyXqF+MBRpKU+J8Oy3PdttdRXqW/Sux/stgy2+BhTmCpLpiulmhciNoicwzdZ9rdUBlSrfQLFRvzI9nYnNo1t8qiveweaT88yB21QNZWM2hclL0XfTKWpk2UfDAlgX36yTEPBAACluo7KofnukzLgEIs77VpjlOlRKW+zC8yN3QqaSIjAJG7+IaDsAfCZ0fF+ly3FBASL9rmeGPagfLRD+dcf4rdPKiNwTGFCmRc5eulcXTgHZzEm0KHHYv+zBhhoYRAdhNvXxoNWG74n8ifgBIEw7sgwTZkr4YHfwkHFCM4HKa5yyaZ3LccU76WW0w8EQF8d+4RdkWAQdIf7I1G7TYWbpjr4PUZbEseH7mWB/YovhHaBqM3zjwlXOalteE1OyXqF+MBRpKU+J8Oy3PdttdRXqW/Sux/stgy2+BhTmCpLpiulmhciNoi6OQ3xfofi2+vBc3Lw+EkV6P3R9e8WKHaQuZmMHyTCxqNC7c2owis5HKLy3UBj0hFXORhlthiu5FiwSt16nKoszk3kqfYQ5sl6pJOLlrmHRsEZJuCAGyHNA4+W/khGrsr6OHWwCU/UD7C3asuo3OEHpRcK/6jNmR0v8ulkZ8yWrwrq6kr0NEfS6B7u7z/O2LaBFVXDPCuKGXGick0cyTKnD6OboSCGQRiCi+ZKPqAMDAbevCzkM0Sh3zXsT9Ta9+sfc4igfMYxiKNM1/ymQCAvz2EgWGNrNAeRiaJDANsDR+x7/EB1sc2uDBxtfPhdI7oP7exNaMaOzN9uInpEGHQZ67yQYukZtvXUWGdHVxHCtAnwGMHVvF9sPBESYNIsn8NXS9kqpocJtI/4Hx4MZ7UX6YVhnxd7VTE2QPw/7ynAznm2HRTfWcExw5iRJQA1N4s+gMTSVpHdxA3EeXsKX2Fhmko7AD6eFT35tghXJV7U2u5VkA02Vj0FHfydEtAM4LH2LqJ9WkRsyvc7zCbA1H+BQ2B+m0pV0kqpKcgNGj78MahO4Bg4Jier1aqltYYpa+kRXHiP8qCNogbhdU3cakrsjDgV3CGJZ6tnOO75lQb0qd/v/Lds9+Dvt/Ikz6hc5XpYn7TOCCGgtP/NPTe8faDMGyt2cY3NFr/EMOV9pwsQfdPU1WTHospmRa5U1iDEQ4eeB64ct1bQ7xKnKAABl7WOB2QrisIrv+HDl1crRlYCjeqohUehHiq+lK4GDgZoEijitUAZd9cW4WQHbQiO3XjnKETeFD70MskPLvUZjDIqoTNezObStrOyBef79MSWYQOHD56IHvgSv5iW5nkd23ilJo7i+3izFkZaOPg0k9xbcscZAHWUNjThobtOzqgBYLNxUlhXK4r7iK9ZThe2dq+R6xQE1dogpJB3sFuWE0vx8XoSqB13WV1TlyoWFh4pdHp0WmspDDzhCnNyzSEV1THn/bVSRTvdxmwKh8lWYwHdQTrmyE+Av/+tQGUxwNus5gQ1IcIjmZutOKU5K4mVv3IxVUjuN2x2HYbsZLT19Y1DftrBtmt99sVH419UJXz03CG","t":1590867430,"sign":"e3a95612d0680282cd030cb150d91fd4"}`

This is the release version for which app or plugin?

**Comment by stevenshen1020** [comment]
Hi, Is there any work around for get tuya's id and key now?

**Comment by RuneNyhuus** [comment]
Need help to this too... the discover do not work anymore.
Can't get id or key

**Comment by Gromga** [comment]
If that that may help, here's the method I used to get my switch's ids and keys
https://www.youtube.com/watch?v=oq0JL_wicKg

**Comment by ApopheniaPays** [comment]
OMFG, could somebody please post instuctions here, instead of a link to some other site? Is this plugin no longer usable?

**Comment by dcbarry** [comment]
> OMFG, could somebody please post instuctions here, instead of a link to some other site? Is this plugin no longer usable?

I share your general frustration with video vs written instructions.   Normally, I would agree.

  I will say though that it is fairly complex (requiring you to set up a developer account on the Tuya site) , and the video -- along with the first pinned post under the video -- with the comment that I needed to activate ALL the options - actually works for getting the keys.

Some of the options on the Tuya website have also slightly changes, but I figured those out -- basically it involves using the left sidebar to navigate to the different locations on their site.

It's a lot of work to write that up --- so maybe you could follow the video and do a write up?

**Comment by jeffmcnabb** [comment]
Welp I got this far, stuck on Socket Hang Up, and that YouTube video has been removed. I have a Tuya IOT account, but how do get ID and key for MY devices into it? The IOT account seems totally separate from the Tuya Smart account. @dcbarry Do you still have the video you can PM me?
