### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by karthiknl0** [AMoo-Miki/homebridge-tuya-lan#187]
Typeerror: callback is not a function
    at RGBTWLightAccessory.<anonymous> (/usr/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:12:13)
    at PlatformAccessory.emit (events.js:198:13)
    at Accessory.PlatformAccessory._associatedHAPAccessory.on (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
    at Accessory.emit (events.js:198:13)
    at Accessory.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Accessory._this._identificationRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:259:12)
    at Identify.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:248:16)
    at Identify.emit (events.js:198:13)
    at Identify.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Identify.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)

**Comment by karthiknl0** [comment]
I keep getting this error after homebridge is running for 5 to 10 mins.. and after that home bridge shuts down
