### ISSUE TITLE
id / localkey

### ISSUE THREAD

**Issue by hohmannc85** [AMoo-Miki/homebridge-tuya-lan#188]
Hey I try for ours to get id and localkey for device and tried different methods!
i am still trying this: https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki

As soon I try to start Tuya-lan-find I get this error:

pi@raspberrypi:~ $ tuya-lan-find --ip 192.168.178.55
/usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175
    let {address, port} = proxy.httpServer.address();
                                           ^

TypeError: Cannot read property 'address' of undefined
    at /usr/local/lib/node_modules/homebridge-tuya-lan/bin/cli.js:175:44
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/proxy.js:62:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/lib/ca.js:130:14
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:988:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/http-mitm-proxy/node_modules/async/dist/async.js:3885:13
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/mkdirp/index.js:48:53
    at FSReqCallback.oncomplete (fs.js:167:21)

can u help me? I already closed all lan connections except wlan0

**Comment by MikeDProducer** [comment]
There is a more updated version of this plugin called Homebridge-Tuya.

**Comment by Gromga** [comment]
If that that may help, here's the method I used to get my switch's ids and keys
https://www.youtube.com/watch?v=oq0JL_wicKg
