### ISSUE TITLE
TypeError: Cannot read property 'devices' of null at new TuyaLan

### ISSUE THREAD

**Issue by djgalati** [AMoo-Miki/homebridge-tuya-lan#194]
I was able to get all 4 of my lights keys and ID's but when i start my homebridge server, it crashes with the error: "TypeError: Cannot read property 'devices' of null at new TuyaLan"

My Config.json is as shown below:
`{
            "platform": "TuyaLan",
            "devices": [
                {
                    "name": "Living Room Light 1",
                    "type": "SimpleLight",
                    "manufacturer": "Tuya",
                    "model": "Smart Wifi Bulb",
                    "id": "xxxxxxxxx",
                    "key": "xxxxxxxxxxx"
                },
                {
                    "name": "Living Room Light 1",
                    "type": "SimpleLight",
                    "manufacturer": "Tuya",
                    "model": "Smart Wifi Bulb",
                    "id": "xxxxxxxxxx",
                    "key": "xxxxxxxxx"
                },
                {
                    "name": "Living Room Light 3",
                    "type": "SimpleLight",
                    "manufacturer": "Tuya",
                    "model": "Smart Wifi Bulb",
                    "id": "xxxxxxxx",
                    "key": "xxxxxxxxxx"
                },
                {
                    "name": "Kitchen Light",
                    "type": "SimpleLight",
                    "manufacturer": "Tuya",
                    "model": "Smart Wifi Bulb",
                    "id": "xxxxxxxxx",
                    "key": "xxxxxxxxxx"
                }`

Got any suggestions to fix this?

**Comment by djgalati** [comment]
This is the full issue:

[7/14/2020, 9:21:07 PM] TypeError: Cannot read property 'devices' of null
    at new TuyaLan (/usr/local/lib/node_modules/homebridge-tuya-lan/index.js:51:43)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by sab0tajue** [comment]
Поддерживаю такая ошибка и у меня

TypeError: Cannot read properties of undefined (reading 'map')
    at new TuyaLan (/usr/local/lib/node_modules/homebridge-tuya-lan/index.js:51:51)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
