### ISSUE TITLE
Cannot discover ids and keys

### ISSUE THREAD

**Issue by feardamhan** [AMoo-Miki/homebridge-tuya-lan#201]
Latest homebridge and tuya-lan plugin 

Have gone through the proxy configuration several times, but when I open the Tuya app on my iPhone I just get errors like this

Failed to intercept secure communications. This could happen due to bad CA certificate.

and

Error: Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1062:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at Socket.done (_tls_wrap.js:567:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  code: 'ECONNRESET'
}

I dont get any ids or keys

Any ideas?

**Comment by CallumHoward** [comment]
I also have this

**Comment by CallumHoward** [comment]
Looks like a duplicate https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/186#issuecomment-629665957

**Comment by RuneNyhuus** [comment]
I have the same problem.. need a fix for this :(

**Comment by Gromga** [comment]
If that that may help, here's the method I used to get my switch's ids and keys
https://www.youtube.com/watch?v=oq0JL_wicKg

**Comment by r3volution11** [comment]
Thanks for the video @Gromga but could you write it up instead? In these kinds of things, for many people, it's easier to read instructions than watch a video.

**Comment by ApopheniaPays** [comment]
Yeah, offsite videos are subject to link decay, and not great if you're having audio problems.

**Comment by dcbarry** [comment]
@r3volution11 @ApopheniaPays  ---   I like  (and prefer) write ups as well, but to be fair, its fairly complex.   I can attest it works, so suggest that as the person requesting a writeup you guys actually do so.   @Gromga did you the favor of pointing out something that works.  He didn't make the video.

**Comment by jdtsmith** [comment]
The roll-your-own-app method I used successfully is [written up here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md).
