### ISSUE TITLE
Error: ERR_SSL_UNSUPPORTED_PROTOCOL

### ISSUE THREAD

**Issue by xmasbogdan** [AMoo-Miki/homebridge-tuya-lan#202]
Using iPhone SE 2020, iOS 14.2 and Homebridge running on a Raspberry Pi 4, I am trying to get the IDs and Keys for my Tuya light switches.

Got this error after following the guide (https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions):

Error: ERR_SSL_UNSUPPORTED_PROTOCOL [Error: 3069979088:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
] {
  library: 'SSL routines',
  function: 'tls_early_post_process_client_hello',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}

**Comment by Hoefnix** [comment]
Same here, iPhone XS iOS14.2 hombridge RasPi2

Error: ERR_SSL_UNSUPPORTED_PROTOCOL [Error: 1995577808:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
] {
  library: 'SSL routines',
  function: 'tls_early_post_process_client_hello',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}

**Comment by tranceme** [comment]
Ditto. I'm seeing same thing. Nothing in the screen for a bit. Then this comes out. Using iOS 14.2 with docker homebridge. 

Error: ERR_SSL_UNSUPPORTED_PROTOCOL [Error: 140273122598216:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1686:
] {
  library: 'SSL routines',
  function: 'tls_early_post_process_client_hello',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}

**Comment by xmasbogdan** [comment]
Any chance to have this issue solved? Has anyone found a solution?

**Comment by Gromga** [comment]
If that that may help, here's the method I used to get my switch's ids and keys
https://www.youtube.com/watch?v=oq0JL_wicKg

**Comment by NoLooseEnds** [comment]
Bump

**Comment by shivanathd** [comment]
HI everyone, I still face this issue ios 15.5 iphone 13 pro max

**Comment by mazafra1** [comment]
I'm having exactly this issue.

Tuya Smart app version: 5.2.0
iPhone 13 on iOS 16.5
Proxy enabled and certificated trusted.

When configuring the proxy on the iPhone I'm getting:
`Error: Error [ERR_TLS_HANDSHAKE_TIMEOUT]: TLS handshake timeout
    at TLSSocket._handleTimeout (_tls_wrap.js:887:22)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ERR_TLS_HANDSHAKE_TIMEOUT'
}`

When opening the Tuya app, I'm getting:
`Error: Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1063:23)
    at TLSSocket.emit (events.js:326:22)
    at net.js:675:12
    at Socket.done (_tls_wrap.js:568:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:675:12) {
  code: 'ECONNRESET'
}`

**Comment by mazafra1** [comment]
> If that that may help, here's the method I used to get my switch's ids and keys
> https://www.youtube.com/watch?v=oq0JL_wicKg

This is a private video, not accessible.

**Comment by mazafra1** [comment]
This issue may be related to this other one: https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/260

**Comment by dcifer1** [comment]
> This issue may be related to this other one: #260

These are definitely related issues, which i've been getting too. any known causes or fixes yet?

**Comment by cbrunnkvist** [comment]
Maybe related to Certificate Pinning being implemented by the iOS app. But then again, why would it error with "unsupported protocol"? No idea, but all of the Tuya `-local`/`-lan` tools seem to suffer from the same situation currently / since a couple of years back. I just gave up the local approach and went with creating a Developer Account and set up a Cloud App and so on, as described by the other "non-local" Tuya plugins & libraries. 🫠

```
Intercepted certificate request
Error: ERR_SSL_UNSUPPORTED_PROTOCOL [Error: 400053BF7F000000:error:0A000102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1677:
] {
  library: 'SSL routines',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}
Error: ERR_SSL_UNSUPPORTED_PROTOCOL [Error: 400053BF7F000000:error:0A000102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1677:
] {
  library: 'SSL routines',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}
```

**Comment by ericmoret** [comment]
Any update on this issue?
