### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by monza258** [AMoo-Miki/homebridge-tuya-lan#220]
Hi, i will get the key from my thermostat i i got some ERROR. Anyone know whats wrong?

```
Error: Error: socket hang up
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.onSocketClose (_tls_wrap.js:1058:23)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12) {
  code: 'ECONNRESET'
}
```

**Comment by wombat86** [comment]
I'm facing the same issue with Thermostat

**Comment by hfagelnour** [comment]
same here

**Comment by StonehengeCreations** [comment]
Same issue here.
