### ISSUE TITLE
Error with two SimpleLight entries in configure.json

### ISSUE THREAD

**Issue by AlainKaim** [AMoo-Miki/homebridge-tuya-lan#26]
Hello

I get an error when I declare in the config.json file two devices as SimpleLight.
The error is : 
/usr/local/lib/node_modules/homebridge-tuya-lan/lib/SimpleLightAccessory.js:24
        const characteristicOn = service.getCharacteristic(Characteristic.On)
                                         ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at SimpleLightAccessory._registerCharacteristics (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/SimpleLightAccessory.js:24:42)
    at TuyaAccessory.BaseAccessory.device.once (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:22:18)
    at Object.onceWrapper (events.js:285:13)
    at TuyaAccessory.emit (events.js:197:13)
    at TuyaAccessory._change (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:240:18)
    at TuyaAccessory._msgHandler (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:176:26)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:4096:9
    at Object.process (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:2344:17)
    at /usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:2252:19
    at Immediate.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:119:16)

If I change the type of either  of the device to Outlet, everything works well.
(I just have to change the in the Home app).
So it is not a big deal, but I wanted to let you know.

Thanks for your work !

**Comment by AMoo-Miki** [comment]
Can you please paste the entire block from your config file that relates to this plugin? put `xxxxx` for your device `id` and `key` values.

There is a scenario where the details that Homebridge has cached about your device, cause conflicts. Solving it involves deleting the `cachedAccessories` file. However, in the latest and yet unreleased version of the plugin, I have tried to identify and handle these bad cached devices. I don't have enough information to say for sure this is your problem but it is, in my view, the most common problem using Homebridge and its plugins.

I would recommend you first try updating the plugin with `npm i -g AMoo-Miki/homebridge-tuya-lan` and restarting Homebridge.

If that doesn't solve the problem, clear the cache manually; delete the file named `cachedAccessories` which is in a folder named `accessories` beside your `config.json` file. Then restart Homebridge.

**Comment by AlainKaim** [comment]
Thanks for your answer.

Updating he plugin was not enough, but deleting the cache file worked.
:)

If you still need my config file, just ask.

Best,
Alain
