### ISSUE TITLE
Help With Air Conditioner Yamato Optimum tuya

### ISSUE THREAD

**Issue by imeSven** [AMoo-Miki/homebridge-tuya-lan#275]
im trying for 1 week to connect with my air conditioners, i have errors and erros if someone can help me out please with this i will kindly apreciate 
[7/14/2022, 9:23:41 PM] [TuyaLan] Ready to handle My Air Conditioner (SimpleLight:3.3) with signature {"1":true,"2":270,"3":27,"4":"cold","5":"strong","18":0,"20":0,"101":0,"105":"off","110":4325951,"113":"0","114":"0","116":4335,"119":"0","120":"off","123":"0018","125":"great","126":"0","127":"0","128":"0","129":"1","130":26,"131":false,"132":false,"133":"0","134":"{\"t\":1656959851,\"s\":false,\"clr\":true}","135":1}

**Comment by imeSven** [comment]
i also get this error 

[7/14/2022, 9:48:59 PM] [Hue] Phoscon-GW: request 12: GET /sensors
[7/14/2022, 9:48:59 PM] [Hue] Phoscon-GW: request 12: 200 OK
[TuyaAccessory] Heard back from AC Daitsu with command 8
[7/14/2022, 9:49:00 PM] [homebridge-tuya-lan] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[7/14/2022, 9:49:00 PM] [homebridge-tuya-lan] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at RotationSpeed.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2030:14)
    at RotationSpeed.Characteristic.updateValue (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at TuyaAccessory.<anonymous> (/homebridge/node_modules/homebridge-tuya-lan/lib/AirConditionerAccessory.js:195:105)
    at TuyaAccessory.emit (node:events:527:28)
    at TuyaAccessory._change (/homebridge/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:387:18)
    at TuyaAccessory._msgHandler_3_3 (/homebridge/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:317:30)
    at /homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:4016:13
    at Object.process (/homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1679:21)
    at /homebridge/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1531:23
[7/14/2022, 9:49:04 PM] [Hue] Phoscon-GW: request 13: GET /sensors
