### ISSUE TITLE
Gosund Plugs command 8 Error

### ISSUE THREAD

**Issue by tolthoff** [AMoo-Miki/homebridge-tuya-lan#80]
I added Gosund Plugs and they show up in HomeKit but the plugs do not respond to on/off commands. Does that mean these are incompatible? Thanks for your help and the great plugin!  I get this message in my logs:

[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Odd message from Dining Room Plug 2 with command 8: { cmd: 8,
  data:
   'ì&ÚiÂ^(6¢¤]}g\b£¸;- â\'\u0007_ëü\u000b\rùkÇ\u00118k\u000e©
5¤2Øîl\\ÁÙ¥V_ºánX' }
[TuyaAccessory] Odd message from Dining Room Plug 2 with command 8: { cmd: 8,
  data:
   'ì&ÚiÂ^(6¢¤]}g\b£¸;- â\'\u0007_ëü\u000b\rùkÇ\u0011ç\u0010\u00054«óN»<4uÃ)X^gP\t³½06\u001büÈ¶;Ýº\u001cï%ÝÏvORô\u0006fN\u0006ë' }

**Comment by AMoo-Miki** [comment]
Please install the latest `rc` release using `npm i -g homebridge-tuya-lan@rc`. 

If you see `Odd message` we will need to dig more. In that case, please post logs that start with `Discovered...` and end with `Raw message from...`; this will let me understand the situation better.

Good luck.

**Comment by AMoo-Miki** [comment]
Thanks @domsammut for confirming. Let's hope @tolthoff also has their problem solved by using the latest `rc`.

**Comment by tolthoff** [comment]
Thanks! I did the update per above and still have the same issue with the plugs. I can turn them on and off on the app but nothing happens in the real world unfortunately:(. Is there anything you need me to send to see what is happening?

**Comment by AMoo-Miki** [comment]
@tolthoff, can you please post any log messages you have for me to piece together where things are going wrong?

**Comment by tolthoff** [comment]
Here are the logs related to the devices using the plugin (the bedroom plug is not in use which is why it can’t find it).:

[TuyaLan] Discovered Dining Room Plug 2 (88607237600194b5e0ba) identified as Outlet (3.1)
[9/14/2019, 3:30:26 PM] [TuyaLan] Connected to Dining Room Plug 2
[TuyaAccessory] Sending first query to Dining Room Plug 2 (3.1)
[9/14/2019, 3:30:26 PM] [TuyaLan] Ready to handle Dining Room Plug 2 (Outlet:3.1) with signature {"1":false,"11":0}
[9/14/2019, 3:30:26 PM] [TuyaLan] Discovered Dining Room Plug 1 (88607237600194b579ca) identified as Outlet (3.1)
[9/14/2019, 3:30:26 PM] [TuyaLan] Connected to Dining Room Plug 1
[TuyaAccessory] Sending first query to Dining Room Plug 1 (3.1)
[9/14/2019, 3:30:26 PM] [TuyaLan] Ready to handle Dining Room Plug 1 (Outlet:3.1) with signature {"1":false,"11":0}

[9/14/2019, 3:30:26 PM] [TuyaLan] Discovered Bedroom Room Plug 1 (88607237600194bfd613) identified as Outlet (3.1)
[9/14/2019, 3:30:38 PM] [TuyaLan] Connected to Bedroom Room Plug 1
[TuyaAccessory] Sending first query to Bedroom Room Plug 1 (3.1)
[9/14/2019, 3:30:38 PM] [TuyaLan] Ready to handle Bedroom Room Plug 1 (Outlet:3.1) with signature {"1":false,"11":0}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[9/14/2019, 3:31:35 PM] [TuyaLan] Failed to discover Bedroom Room Plug 2 (88607237600194bfd689) in time but will keep looking.
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":false}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Bedroom Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
   hoobs : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x
pam_unix(sudo:session): session opened for user root by (uid=0)
   hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 3696
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 1 {"1":false}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":true}
[TuyaAccessory] Sending Dining Room Plug 2 {"1":false}
   hoobs : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x

**Comment by AMoo-Miki** [comment]
While you have the logs open, manually turn one of the plus on or off with its physical button. Do you see an error in the logs?

**Comment by tolthoff** [comment]
Ok. Here is what I got:

[9/15/2019, 7:40:39 PM] ReferenceError: cleanMsg is not defined
    at TuyaAccessory._msgHandler_3_1 (/usr/local/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:214:21)
    at queue (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:3205:13)
    at Object.process (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1431:21)
    at setImmediate$1 (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:1289:23)
    at Immediate.defer (/usr/local/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:73:45)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[9/15/2019, 7:40:39 PM] Got SIGTERM, shutting down Homebridge...
[9/15/2019, 7:40:39 PM] [Loft] INFO - shutdown
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service RestartSec=3s expired, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 1.
Stopped Homebridge.
Started Homebridge.

**Comment by AMoo-Miki** [comment]
Great hold on.
