### ISSUE TITLE
RGBTWOutlet - Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jlq76** [AMoo-Miki/homebridge-tuya-lan#95]
Hi,

Trying to add an RGBTWOutlet leads to the error below.
When using the simple "Outlet" type for that same device, I can only control the RGB led on the outlet but not the outlet itself. 
(I did it as a smoke test to check that the device is responding and id/keys are correct)

[2019-10-7 12:37:40] [TuyaLan] Ready to handle Office Color Plug (RGBTWOutlet:3.1) with signature {"1":false,"2":"colour","3":255,"4":85,"5":"ff00040167ffff","6":"bd76000168ffff","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000","101":false,"102":0}
[2019-10-7 12:37:40] TypeError: Cannot read property 'toString' of undefined
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:54:59)
    at RGBTWOutletAccessory._verifyCachedPlatformAccessory (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/lib/RGBTWOutletAccessory.js:28:45)
    at RGBTWOutletAccessory._registerCharacteristics (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/lib/RGBTWOutletAccessory.js:43:14)
    at TuyaAccessory.BaseAccessory.device.once (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:22:18)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at TuyaAccessory.emit (events.js:214:7)
    at TuyaAccessory._change (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:387:18)
    at TuyaAccessory._msgHandler_3_1 (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/lib/TuyaAccessory.js:248:48)
    at queue (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-tuya-lan/node_modules/async/dist/async.js:3205:13)
[2019-10-7 12:37:40] Got SIGTERM, shutting down Homebridge...

**Comment by jlq76** [comment]
Below is a quick & dirty solution that seems to work.
No error anymore and outlets are correctly detected and controlled in homekit (both power and light)

in RGBTWOutletAccessory.js

in _verifyCachedPlatformAccessory():
	I replaced 
`        let outletService = this.accessory.getServiceByUUIDAndSubType(Service.Outlet, 'outlet');`
	by 
`        let outletService = this.accessory.getService(Service.Outlet);`
		
		
in _registerCharacteristics(dps):
	I replaced:
`		const outletService = this.accessory.getServiceByUUIDAndSubType(Service.Outlet, 'outlet');`
	by
`        const outletService = this.accessory.getService(Service.Outlet); `
